services:
  - type: web
    name: samantha-josette
    env: node
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 